"""replace coach fields with coach_data

Revision ID: 59868ad75286
Revises: a02fd88b4481
Create Date: 2026-03-21 16:11:31.004679

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '59868ad75286'
down_revision: Union[str, None] = 'a02fd88b4481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionfeedback', sa.Column('coach_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('sessionfeedback', 'tone_analysis')
    op.drop_column('sessionfeedback', 'coach_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionfeedback', sa.Column('coach_analysis', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessionfeedback', sa.Column('tone_analysis', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sessionfeedback', 'coach_data')
    # ### end Alembic commands ###
