"""added last activity at for sessions to track time active

Revision ID: f48f410ec41a
Revises: 59868ad75286
Create Date: 2026-03-21 21:46:11.141666

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f48f410ec41a'
down_revision: Union[str, None] = '59868ad75286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('session', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE session SET last_activity_at = started_at WHERE last_activity_at IS NULL")
    op.alter_column('session', 'last_activity_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'last_activity_at')
    # ### end Alembic commands ###
